linters:
  enable:
    - gofmt
    - gocyclo
    - golint
    - misspell
    - typecheck
    - errcheck
issues:
  exclude:
   # staticcheck
    - 'SA1019: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.'