# Start from golang v1.12.7 base image
FROM golang:1.12.7 as builder

RUN apt-get update \
  && apt-get install -y vim libpcap-dev\
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install unzip

RUN curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_64.zip && \
    unzip -o protoc-3.9.1-linux-x86_64.zip -d /usr/local bin/protoc && \
    unzip -o protoc-3.9.1-linux-x86_64.zip -d /usr/local include/* && \
    rm -rf protoc-3.9.1-linux-x86_64.zip

RUN go get -u github.com/golang/protobuf/protoc-gen-go
RUN mkdir -p /go/src/github.com/google && \
    git clone --branch master https://github.com/googleapis/googleapis /go/src/github.com/googleapis/googleapis && \
    git clone --branch master https://github.com/openconfig/gnmi /go/src/github.com/openconfig/gnmi && \
    git clone --branch master https://github.com/abhilashendurthi/p4runtime /go/src/github.com/abhilashendurthi/p4runtime


# Set the Current Working Directory inside the container
WORKDIR /root/testvectors-runner

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY . . 

# Compile protos
RUN ./compile-protos.sh

#Build go binary
RUN go build -o ./cmd/main/tv_runner ./cmd/main/testvectors-runner.go



# Docker image to run tv_runner with stratum_bmv2 switch
# Use "make switch" to start the switch and "make test" to run tests

FROM opennetworking/mn-stratum

RUN apt-get update && apt-get install -yq make vim

WORKDIR /root

#RUN mkdir -p tv_runner
COPY --from=builder /root/testvectors-runner/cmd/main/tv_runner ./tv_runner
COPY ./tools/Makefile ./Makefile

RUN mkdir ./tools
COPY ./tools/bmv2 ./tools/bmv2/

RUN mkdir -p tv/bmv2

RUN mkdir ./logs

WORKDIR /root

ENTRYPOINT ["/bin/bash"]

